version: '3.8'
services:
  gateway:
    build: ./gateway
    image: gateway_image
    container_name: gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
      - postgres
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
#      - TZ=Europe/Moscow
  server:
    build: ./server
    image: server_image
    container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shareit
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr
#      - TZ=Europe/Moscow
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr
#      - TZ=Europe/Moscow